### PR TITLE
Replace http_req crate with reqwest

### LINKED ISSUE #42: Replace http_req crate
We need to replace `http_req` because of the following reasons:

1. Error handling is troublesome because `http_req` errors do not implement `Error` trait.
2. Errors in `http_req` are very ambiguous (eg. "Error: IO error").
3. `http_req` does not support disabling SSL checks.
4. No built-in JSON support.

Good candidate would be `reqwest` crate. It is a bit bloated and hopefully we can configure it so that we don't need to install all sub-dependencies.

### PR DESCRIPTION
**Pull request by ollipa**
- Replace `http_req` crate with `reqwest`.
- Improved error handling in InfluxDB exporter (better error messages).
- Accept invalid certificates in HTTP collector.
- Add tests for InfluxDB exporter and HTTP collector.

Closes #42

### CODE REVIEW

File: src/error.rs [hunk 1]
```diff
@@ -61,28 +76,28 @@ impl fmt::Display for Error {
...
+    fn set_cause(self, cause: impl error::Error + 'static) -> Self;
 
-    fn context(self, context: &str) -> Self;
+    fn set_context(self, context: &str) -> Self;
 }
 
 impl<T> ResultError for Result<T> {
-    fn source(self, source: &str) -> Self {
-        self.map_err(|e| e.source(source))
+    fn set_source(self, source: &str) -> Self {
```
Comment (adarshk7) [inline src/error.rs:92]: Just asking what the rationale for changing it to `set_*` was as we discussed last time that this wasn't the convention?

Comment (ollipa) [reply src/error.rs:92]: Convention is to use use getter `source` and setter `set_source` but not `get_source` for getters.

Comment (ollipa) [reply src/error.rs:92]: https://doc.rust-lang.org/1.0.0/style/style/naming/README.html
> A method foo(&self) -> &T for getting the current value of the field.

> A method set_foo(&self, val: T) for setting the field. (The val argument here may take &T or some other type, depending on the context.)
